timeout = 120

[[jobs]]
name = "list schedules"
sql = """
SELECT schedule_id, name
FROM schedules
LIMIT 100"""
spreadsheetid = "1s3ShDoegxjR5az-IX826vhApE6sCnGoEClxHuKUatHo"
sheetname = "Sheet1"

[[jobs]]
name = "list modes"
sql = """
SELECT mode_id, name
FROM modes
LIMIT 80"""
spreadsheetid = "1s3ShDoegxjR5az-IX826vhApE6sCnGoEClxHuKUatHo"
sheetname = "Sheet2"
